// <auto-generated />
using System;
using Conduit.Comments.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Conduit.Comments.DataAccess.Migrations
{
    [DbContext(typeof(CommentsContext))]
    [Migration("20220218210203_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthorDbModelAuthorDbModel", b =>
                {
                    b.Property<Guid>("FollowedsId")
                        .HasColumnType("uuid")
                        .HasColumnName("followeds_id");

                    b.Property<Guid>("FollowersId")
                        .HasColumnType("uuid")
                        .HasColumnName("followers_id");

                    b.HasKey("FollowedsId", "FollowersId")
                        .HasName("pk_author_follower");

                    b.HasIndex("FollowersId")
                        .HasDatabaseName("ix_author_follower_followers_id");

                    b.ToTable("author_follower", (string)null);
                });

            modelBuilder.Entity("Conduit.Comments.DataAccess.Articles.ArticleDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_article");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_article_author_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_article_slug");

                    b.ToTable("article", (string)null);
                });

            modelBuilder.Entity("Conduit.Comments.DataAccess.Authors.AuthorDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_author");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_author_username");

                    b.ToTable("author", (string)null);
                });

            modelBuilder.Entity("Conduit.Comments.DataAccess.Comments.CommentDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_comment_article_id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_comment_author_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_comment_created_at");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("AuthorDbModelAuthorDbModel", b =>
                {
                    b.HasOne("Conduit.Comments.DataAccess.Authors.AuthorDbModel", null)
                        .WithMany()
                        .HasForeignKey("FollowedsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_author_follower_author_followeds_id");

                    b.HasOne("Conduit.Comments.DataAccess.Authors.AuthorDbModel", null)
                        .WithMany()
                        .HasForeignKey("FollowersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_author_follower_author_followers_id");
                });

            modelBuilder.Entity("Conduit.Comments.DataAccess.Articles.ArticleDbModel", b =>
                {
                    b.HasOne("Conduit.Comments.DataAccess.Authors.AuthorDbModel", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_author_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Conduit.Comments.DataAccess.Comments.CommentDbModel", b =>
                {
                    b.HasOne("Conduit.Comments.DataAccess.Articles.ArticleDbModel", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_article_article_id");

                    b.HasOne("Conduit.Comments.DataAccess.Authors.AuthorDbModel", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_author_author_id");

                    b.Navigation("Article");

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
